name: Build and Push Docker Images

on:
  push:
    tags:
      - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version from tag
        id: meta
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Build and push broker
        uses: docker/build-push-action@v4
        with:
          context: ./broker/service
          push: true
          tags: |
            realmtrix/broker:latest
            realmtrix/broker:${{ steps.meta.outputs.VERSION }}

      - name: Build and push console
        uses: docker/build-push-action@v4
        with:
          context: ./broker/console
          push: true
          tags: |
            realmtrix/console:latest
            realmtrix/console:${{ steps.meta.outputs.VERSION }}
