// TODO: These types will be generated by Prisma
// Run: npm run prisma:generate

// Placeholder types until Prisma schema is created
export interface DbRealm {
  id: string;
  name: string;
  description?: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface DbMember {
  id: string;
  realmId: string;
  name: string;
  roles: string[];
  createdAt: Date;
  updatedAt: Date;
}

export interface DbBridge {
  id: string;
  sourceRealmId: string;
  targetRealmId: string;
  contract: any;
  status: 'pending' | 'active' | 'suspended';
  createdAt: Date;
  updatedAt: Date;
}

export interface DbPolicy {
  id: string;
  name: string;
  type: string;
  rules: any;
  createdAt: Date;
  updatedAt: Date;
}

export interface DbCapability {
  id: string;
  realmId: string;
  name: string;
  description?: string;
  version: string;
  schema: any;
  access: string;
  createdAt: Date;
  updatedAt: Date;
}
